server:
  port: 10088

spring:
  application:
    name: StudyBackend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/study?useUnicode=true&characterEncoding=utf-8
    username: root
    password: onlee#forever@123
